# My variables
name: Out of Breath
description: A life lived.
google_verification: null
email: oobguy@outofbreath.org


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Feed
plugins:
  - jekyll-feed
  - jekyll-sitemap
